/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.CPlaylists;
import Model.User;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author pudim
 */
public class VPlaylists extends javax.swing.JFrame {

    /**
     * Creates new form VSpotfei
     * @param vS
     * @param loggedUser
     */
    public VPlaylists(VSpotfei vS, User loggedUser) {
        initComponents();
        c = new CPlaylists(this, loggedUser);
        this.vS = vS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlaylistName = new javax.swing.JTextField();
        lblFilter = new javax.swing.JLabel();
        btSearch = new javax.swing.JButton();
        lblPlaylist = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();
        btDelMusic = new javax.swing.JButton();
        spMain = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        txtMusicId = new javax.swing.JTextField();
        btDelPlaylist = new javax.swing.JButton();
        lblPlaylistName = new javax.swing.JLabel();
        lblMusicId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaInfo = new javax.swing.JTextArea();
        lblDelPlaylist = new javax.swing.JLabel();
        lblDelMusic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFilter.setForeground(new java.awt.Color(153, 153, 153));
        lblFilter.setText("nome da playlist.");

        btSearch.setText("Procurar");
        btSearch.setActionCommand("btSearch");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        lblPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPlaylist.setText("PLaylists");

        btHome.setText("home");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        btDelMusic.setText("excluir");
        btDelMusic.setActionCommand("btSearch");
        btDelMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelMusicActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spMain.setViewportView(jTable1);

        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSearchMouseEntered(evt);
            }
        });

        btDelPlaylist.setText("excluir");
        btDelPlaylist.setActionCommand("btSearch");
        btDelPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelPlaylistActionPerformed(evt);
            }
        });

        lblPlaylistName.setForeground(new java.awt.Color(153, 153, 153));
        lblPlaylistName.setText("Nome da playlist.");

        lblMusicId.setForeground(new java.awt.Color(153, 153, 153));
        lblMusicId.setText("id da musica.");

        txtaInfo.setColumns(20);
        txtaInfo.setRows(5);
        jScrollPane2.setViewportView(txtaInfo);

        lblDelPlaylist.setForeground(new java.awt.Color(153, 153, 153));
        lblDelPlaylist.setText("Excluir playlist.");

        lblDelMusic.setForeground(new java.awt.Color(153, 153, 153));
        lblDelMusic.setText("Excluir da playlist.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMain)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMusicId, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(txtPlaylistName))
                            .addComponent(lblPlaylistName)
                            .addComponent(lblMusicId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDelMusic)
                            .addComponent(lblDelPlaylist)
                            .addComponent(btDelMusic)
                            .addComponent(btDelPlaylist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilter)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearch)
                        .addGap(54, 54, 54)
                        .addComponent(lblPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPlaylist)
                    .addComponent(btHome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(spMain, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaylistName)
                            .addComponent(lblDelPlaylist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaylistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDelPlaylist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDelMusic)
                            .addComponent(lblMusicId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btDelMusic)
                            .addComponent(txtMusicId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        vS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btHomeActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        c.loadPlaylists();
    }//GEN-LAST:event_btSearchActionPerformed

    private void txtSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseEntered
        c.showSearchHistory();
    }//GEN-LAST:event_txtSearchMouseEntered

    private void btDelPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelPlaylistActionPerformed
        c.deletePlaylist();
    }//GEN-LAST:event_btDelPlaylistActionPerformed

    private void btDelMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelMusicActionPerformed
        c.deleteMusicPlaylist();
    }//GEN-LAST:event_btDelMusicActionPerformed

    public JButton getBtDelMusic() {
        return btDelMusic;
    }

    public void setBtDelMusic(JButton btDelMusic) {
        this.btDelMusic = btDelMusic;
    }

    public JButton getBtDelPlaylist() {
        return btDelPlaylist;
    }

    public void setBtDelPlaylist(JButton btDelPlaylist) {
        this.btDelPlaylist = btDelPlaylist;
    }

    public JButton getBtHome() {
        return btHome;
    }

    public void setBtHome(JButton btHome) {
        this.btHome = btHome;
    }

    public JButton getBtSearch() {
        return btSearch;
    }

    public void setBtSearch(JButton btSearch) {
        this.btSearch = btSearch;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JLabel getLblDelMusic() {
        return lblDelMusic;
    }

    public void setLblDelMusic(JLabel lblDelMusic) {
        this.lblDelMusic = lblDelMusic;
    }

    public JLabel getLblDelPlaylist() {
        return lblDelPlaylist;
    }

    public void setLblDelPlaylist(JLabel lblDelPlaylist) {
        this.lblDelPlaylist = lblDelPlaylist;
    }

    public JLabel getLblFilter() {
        return lblFilter;
    }

    public void setLblFilter(JLabel lblFilter) {
        this.lblFilter = lblFilter;
    }

    public JLabel getLblMusicId() {
        return lblMusicId;
    }

    public void setLblMusicId(JLabel lblMusicId) {
        this.lblMusicId = lblMusicId;
    }

    public JLabel getLblPlaylist() {
        return lblPlaylist;
    }

    public void setLblPlaylist(JLabel lblPlaylist) {
        this.lblPlaylist = lblPlaylist;
    }

    public JLabel getLblPlaylistName() {
        return lblPlaylistName;
    }

    public void setLblPlaylistName(JLabel lblPlaylistName) {
        this.lblPlaylistName = lblPlaylistName;
    }

    public JScrollPane getSpMain() {
        return spMain;
    }

    public void setSpMain(JScrollPane spMain) {
        this.spMain = spMain;
    }

    public JTextField getTxtMusicId() {
        return txtMusicId;
    }

    public void setTxtMusicId(JTextField txtMusicId) {
        this.txtMusicId = txtMusicId;
    }

    public JTextField getTxtPlaylistName() {
        return txtPlaylistName;
    }

    public void setTxtPlaylistName(JTextField txtPlaylistName) {
        this.txtPlaylistName = txtPlaylistName;
    }

    public JTextField getTxtSearch() {
        return txtSearch;
    }

    public void setTxtSearch(JTextField txtSearch) {
        this.txtSearch = txtSearch;
    }

    public JTextArea getTxtaInfo() {
        return txtaInfo;
    }

    public void setTxtaInfo(JTextArea txtaInfo) {
        this.txtaInfo = txtaInfo;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VPlaylists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VPlaylists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VPlaylists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VPlaylists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//            }
//        });
//    }
    
    VSpotfei vS;
    CPlaylists c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelMusic;
    private javax.swing.JButton btDelPlaylist;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btSearch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDelMusic;
    private javax.swing.JLabel lblDelPlaylist;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblMusicId;
    private javax.swing.JLabel lblPlaylist;
    private javax.swing.JLabel lblPlaylistName;
    private javax.swing.JScrollPane spMain;
    private javax.swing.JTextField txtMusicId;
    private javax.swing.JTextField txtPlaylistName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextArea txtaInfo;
    // End of variables declaration//GEN-END:variables
}
